### ISSUE TITLE
File list widget is empty until interacting with it

### ISSUE THREAD

**Issue by betatim** [hadim/jupyter-archive#22]
When I open the binder example https://mybinder.org/v2/gh/hadim/jupyter-archive/master?urlpath=lab in Firefox 70.0b11 (64-bit) on OSX the list of files and directories is empty. When I click into the area the files appear instantly.

It doesn't happen always. One way to increase the chances of it happening is to open the binder in a new tab and only switch there once the page has fully loaded.

<img width="324" alt="Screenshot 2019-10-11 at 07 29 28" src="https://user-images.githubusercontent.com/1448859/66626537-e18c5d00-ebf8-11e9-9c6e-2dc992252bff.png">

**Comment by hadim** [comment]
This is a weird bug. Are you sure this is related to this extension?

Here is the relevant code: https://github.com/hadim/jupyter-archive/blob/f7addd7db566d4c728f47b77930760ac118994a3/src/index.ts#L186

Nothing crazy is done.

**Comment by hadim** [comment]
I cannot reproduce the issue on Ubuntu with Firefox 70b13. Could you try on Chromium and OSX to see if you can reproduce?

If this bug is not ultra-specific to your configuration, it's very likely a JLab bug.

**Comment by betatim** [comment]
In Chrome this doesn't happen for me either :-/

**Comment by hadim** [comment]
Ok so it's Firefox 70/OSX specific. Can you try on Firefox 69?

**Comment by betatim** [comment]
I'll try but unlikely to remember to install and test it :-/

**Comment by fcollonval** [comment]
This is not related to this extension - I get the delay (almost all the time on binder).
