### ISSUE TITLE
Issue with labextension

### ISSUE THREAD

**Issue by hadim** [hadim/jupyter-archive#29]
When I install 0.5.4 from conda, I have an error related to settings when loading the JLab interface.

I also tried uninstalling the lab extension and installing manually with `jupyter labextension uninstall @hadim/jupyter-archive` but I still have the same error:

![image](https://user-images.githubusercontent.com/528003/69248953-29e55600-0b7b-11ea-8d16-ecf1dcdf0453.png)

```
JupyterLab extension jupyter-archive is activated!
lab/api/settings/@hadim/jupyter-archive:archive?1574261408927:1 Failed to load resource: the server responded with a status of 404 (Not Found)
index.js:170 Error: Invalid response: 404 Not Found
    at SettingManager.fetch (index.js:41)
    at async SettingRegistry.reload (settingregistry.js:235)
(anonymous) @ index.js:170
dialog.js:32 Showing error: Error: Invalid response: 404 Not Found
    at SettingManager.fetch (index.js:41)
    at async SettingRegistry.reload (settingregistry.js:235)
```

**Comment by hadim** [comment]
ping @fcollonval

**Comment by fcollonval** [comment]
@hadim which version of Jupyterlab are you using?

**Comment by hadim** [comment]
The latest `1.2.3`.

**Comment by hadim** [comment]
Does that mean a jupyter-archive version is only compatible with a specific JLab version? That would suck...

**Comment by fcollonval** [comment]
There is something I can not explain. 

The `schema/archive.json` is not in the extension archive inside the conda package. But I checked it is in the extension archive in the source archive on pypi.org from which the conda package is built.

Can I trigger a built of the conda package to see if it a reproductible behavior or a one-time error?

**Comment by hadim** [comment]
Yes you need to open a PR on the feedstock repo: https://github.com/conda-forge/jupyter-archive-feedstock/pulls

You can also build it locally with Docker if needed.

**Comment by hadim** [comment]
@fcollonval here is a detailed description of the issue: https://github.com/conda-forge/jupyter-archive-feedstock/issues/6

**Comment by hadim** [comment]
@fcollonval Actually I also have the error when installing from `pip`. See https://github.com/conda-forge/jupyter-archive-feedstock/issues/6#issuecomment-557596419

Is that possible it was working for us before because we had the dev version installed in our system?

**Comment by hadim** [comment]
So or whatever reason installation via `pip`, `conda` and even `jupyter labextension install ...`, `share/jupyter/lab/schemas/@hadim/jupyter-archive` is not populated with the schema file.

The only way to make it work is manually copying `archive.json` to it.

**Comment by hadim** [comment]
Fixed by https://github.com/hadim/jupyter-archive/commit/3f089ebcb85ca6bc8eee9ea69ada868932530bc5

**Comment by fcollonval** [comment]
@hadim thank you for fixing this one!
