### ISSUE TITLE
Consider streaming

### ISSUE THREAD

**Issue by ryanlovett** [hadim/jupyter-archive#3]
Hiya, I also wrote [an archiver](https://github.com/ryanlovett/jupyter-tree-download) though I see this one may get integrated into jupyter_server. Please consider supporting streaming the download which is critical for large archives. Otherwise the server may time out waiting for the archive to build.

**Comment by hadim** [comment]
Good idea indeed. Interested to submit a PR?

**Comment by hadim** [comment]
From https://gist.github.com/seriyps/3773703,

I think we would need something similar to this:

```python
    @tornado.web.asynchronous
    @tornado.gen.engine
    def get(self):
        self.set_header("Content-Type", "text/plain")
        self.set_header("Content-Length", os.path.getsize(self.path))
        self.flush()
        # "with" statement didn't work properly in this context (didn't release
        # resources when socket inproperly closed by client)
        # with open(self.path, "rb") as fd:
        #     data = fd.read(self.CHUNK_SIZE)
        #     while data:
        #         self.write(data)
        #         yield tornado.gen.Task(self.flush)
        #         data = fd.read(self.CHUNK_SIZE)
        fd = open(self.path, "rb")
        data = fd.read(self.CHUNK_SIZE)
        while data:
            self.write(data)
            yield tornado.gen.Task(self.flush)
            data = fd.read(self.CHUNK_SIZE)
        fd.close()
        self.finish()
```

**Comment by hadim** [comment]
But we need to mix it with live compression of the archive.

**Comment by hadim** [comment]
The following could be helpful for the zip streaming part: https://gist.github.com/bancek/7fe5fe0476e81495f99633cf91b6ee29

**Comment by hadim** [comment]
Note that the above snippet is for ZIP only.

**Comment by ryanlovett** [comment]
I've got streaming in https://github.com/ryanlovett/jupyter-tree-download/blob/master/jupyter_tree_download/handlers.py, though I used external programs to do the compression.

**Comment by hadim** [comment]
Yes, I saw that but I don't want to rely on external programs. We should keep the code Python only if we want to merge this to the notebook.

Streaming seems easy but integrating it with Zip compression seems to be more tricky.

I can't have a look right now so if you want to try it in the meantime you're welcome.

**Comment by hadim** [comment]
Looks like streaming was easier than excepted since everything was already here. I just needed to add the magic `await` keyword calling `self.flush`. See https://github.com/hadim/jupyter-archive/commit/dd514277613085fc1a5ee72f7ba8d83bb9c69153

In my test, a 200 Mo file can start being downloaded immediately without bocking the server.

I will close, please re-open if needed.

**Comment by ryanlovett** [comment]
Awesome, thanks.

**Comment by hadim** [comment]
Also, I have published the extension to NPM and Pypi for easy installing.
