### ISSUE TITLE
file not found error

### ISSUE THREAD

**Issue by lwasser** [hadim/jupyter-archive#34]
hi there @hadim i'm testing out this extension for our jupyter hub. it looks like a great tool! When i load it locally on my machine - i'm getting "file not found" errors when i attemt to download a directory. The error looks like this:

```
Firefox can’t find the file at http://localhost:8888/directories/0-professional-certificate?archiveToken=h86we7ln86agc3zwhs89&archiveFormat=zip&_xsrf=2|23bbaae0|b5712342d851a6ec0a4a8e7fe6b64323|1588721445.
```
or just a 404 error.

Is there anything that i can try to figure out why this is happening? i'm trying to find a way for my students to back up their work on our hub before i shut it down at the end of the semester. this tool could work if i can get it to work! thank you for any suggestions :)

**Comment by hadim** [comment]
Hi @lwasser 

Can you give me the JLab version you are using?

**Comment by hadim** [comment]
I have just tested with Chrome and Firefox using `jupyter-archive==0.6.2` and `jlab==2.1.0`.

Maybe looking at the logs of the jupyter server could help?

I don't use Hub so I don't know whether it works there.

ping @fcollonval

**Comment by peiweiliu** [comment]
hi @hadim, I think i encounter the similar problem. My JLab version is 2.1.5.

- I installed this extension by JLab and all looks good.
<img width="372" alt="Screen Shot 2020-07-30 at 7 28 38 PM" src="https://user-images.githubusercontent.com/43423821/88984219-0a223800-d29b-11ea-9576-b669138b24e6.png">
<img width="323" alt="Screen Shot 2020-07-30 at 7 31 09 PM" src="https://user-images.githubusercontent.com/43423821/88984322-4bb2e300-d29b-11ea-82f7-a55d1a45064b.png">

- But, when I click it, **it shows "404: NOT Found".**

**How to make sure all is set well? Or, do you have any suggestions for me to check out?** Thank you!:)

-Peiwei

**Comment by peiweiliu** [comment]
Works now. I am not sure which action I did is the key point to kill this issue because i try a lot. But probably it works after i install the Node.js. The document says that **In order to install JupyterLab extensions, you need to have Node.js installed**.
<img width="763" alt="Screen Shot 2020-07-31 at 1 50 45 AM" src="https://user-images.githubusercontent.com/43423821/89004879-293bbc80-d2d1-11ea-8475-505eb7340456.png">
check out more info here: https://jupyterlab.readthedocs.io/en/stable/user/extensions.html
Hope this helps if you are in the same trouble.
-Peiwei

**Comment by fcollonval** [comment]
Hey @peiweiliu did you install the python package? See https://github.com/hadim/jupyter-archive#installation

And indeed, you need nodejs to include extension within JupyterLab.

@lwasser did you succeed to fix your problem? I deployed recently a jupyterhub and got no problem with this extension. You need to be sure that both the lab extension and the python package are installed in the user server.

**Comment by peiweiliu** [comment]
> Hey @peiweiliu did you install the python package? See https://github.com/hadim/jupyter-archive#installation
> 
> And indeed, you need nodejs to include extension within JupyterLab.
> 
> @lwasser did you succeed to fix your problem? I deployed recently a jupyterhub and got no problem with this extension. You need to be sure that both the lab extension and the python package are installed in the user server.

yes, i've installed the python packages. so it seems it is not the reason. I will post more troubleshooting details once i realize which is the key point. Thank you for your reply and your amazing extension! @fcollonval -Peiwei

**Comment by fcollonval** [comment]
The merit goes to @hadim :wink:

**Comment by hadim** [comment]
See https://github.com/hadim/jupyter-archive/issues/40

**Comment by fcollonval** [comment]
Closing this as the original author did not brought any new elements
