### ISSUE TITLE
Allow excluding hidden directories

### ISSUE THREAD

**Issue by albertmichaelj** [hadim/jupyter-archive#35]
First of all, thanks for this extension! It is going to be a huge help for me. One thing that would be great to be able to do is set a configuration that excludes hidden directories. I teach a class using a JupyterHub K8s deployment where the students need to be able to take the material with them, but they don't need all of the hidden directories that inevitably pop up around a docker container. This is particularly true because all of the class material is in github projects, and the students pull it down using nbgitpuller, so they end up with `.git` folders everywhere which aren't useful to them after the class is over.

Would you have any interest in adding a configuration that allows to exclude hidden directories? I looked through the code briefly, and I don't think this is implemented, but I could be wrong.

**Comment by hadim** [comment]
I just saw your message now. Sorry for that!

You're right it's not implemented. I don't think I'll have time to do that myself soon but I would be happy to review a PR.
