### ISSUE TITLE
head method not needed

### ISSUE THREAD

**Issue by fcollonval** [hadim/jupyter-archive#8]
I think the head method for the handler is not needed. 

https://github.com/hadim/jupyter-archive/blob/55fbf191ab3b055e304de05e8b4b9e7af6583afa/jupyter_archive/handlers.py#L48
It's useful only for file to get some information on them without their content.

**Comment by hadim** [comment]
Closed by 7ac9295cd05eea2b9ea00eb41248ef14582e0641
